export const iconEmojiMap: Record<string, string> = {
    plane: "✈️",
    car: "🚗",
    bus: "🚌",
    train: "🚆",
    ship: "🚢",
    bike: "🚲",
    walk: "🚶",
    route: "📍",
    from: "🅰️",
    to: "🅱️",
    home: "🏠",
    office: "🏢",
    school: "🏫",
    hospital: "🏥",
    restaurant: "🍽️",
    coffee: "☕",
    shop: "🛒",
    park: "🌳",
    museum: "🏛️",
    hotel: "🏨",
    person: "👤",
    group: "👥",
    info: "ℹ️",
    warning: "⚠️",
    danger: "❗",
    star: "⭐",
    photo: "📷",
    camera: "📸",
    note: "📝",
    chat: "💬",
    gold: "🥇",
    silver: "🥈",
    coal: "🪨",
    oil: "🛢️",
    gas: "⛽",
    iron: "⚙️",
    copper: "🟧",
    diamond: "💎",
    stone: "🪨",
    mining: "⛏️",
    factory: "🏭",
    "power-plant": "🔌",
    refinery: "🏭",
    warehouse: "📦",
    construction: "🏗️",
    shipyard: "🏗️",
    airport: "🛫",
    port: "⚓",
    textile: "🧵",
    agriculture: "🌾",
    mountain: "⛰️",
    river: "🌊",
    lake: "💧",
    forest: "🌲",
    desert: "🏜️",
    volcano: "🌋",
    island: "🏝️",
    beach: "🏖️",
    castle: "🏰",
    temple: "🛕",
    monument: "🗿",
    tomb: "🪦",
    ruin: "🏚️",
    battlefield: "⚔️",
    "ancient-city": "🏛️",
};

// Icon label mapping - used for display names
export const iconLabelMap: Record<string, string> = {
    plane: "Plane",
    car: "Car",
    bus: "Bus",
    train: "Train",
    ship: "Ship",
    bike: "Bike",
    walk: "Walk",
    route: "Route",
    from: "From",
    to: "To",
    home: "Home",
    office: "Office",
    school: "School",
    hospital: "Hospital",
    restaurant: "Food",
    coffee: "Coffee",
    shop: "Shop",
    park: "Park",
    museum: "Museum",
    hotel: "Hotel",
    person: "Person",
    group: "Group",
    info: "Info",
    warning: "Warning",
    danger: "Danger",
    star: "Highlight",
    photo: "Photo spot",
    camera: "Camera",
    note: "Note",
    chat: "Comment",
    gold: "Gold",
    silver: "Silver",
    coal: "Coal",
    oil: "Oil",
    gas: "Natural Gas",
    iron: "Iron",
    copper: "Copper",
    diamond: "Diamond",
    stone: "Stone",
    mining: "Mining",
    factory: "Factory",
    "power-plant": "Power Plant",
    refinery: "Refinery",
    warehouse: "Warehouse",
    construction: "Construction",
    shipyard: "Shipyard",
    airport: "Airport",
    port: "Port",
    textile: "Textile",
    agriculture: "Agriculture",
    mountain: "Mountain",
    river: "River",
    lake: "Lake",
    forest: "Forest",
    desert: "Desert",
    volcano: "Volcano",
    island: "Island",
    beach: "Beach",
    castle: "Castle",
    temple: "Temple",
    monument: "Monument",
    tomb: "Tomb",
    ruin: "Ruin",
    battlefield: "Battlefield",
    "ancient-city": "Ancient City",
};

// Helper function to get emoji from icon key
export function getIconEmoji(iconKey: string): string {
    return iconEmojiMap[iconKey] ?? "📍";
}

// Helper function to get label from icon key
export function getIconLabel(iconKey: string): string {
    return iconLabelMap[iconKey] ?? iconKey;
}

// Reverse lookup: label -> key
export const labelToIconKeyMap: Record<string, string> = Object.fromEntries(
    Object.entries(iconLabelMap).map(([key, label]) => [label, key])
);
